name: SpaMOAL
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - _sysroot_linux-64_curr_repodata_hack=3=h69a702a_16
  - arpack=3.7.0=hdefa2d7_2
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_33
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.11.0=h470a237_1
  - ca-certificates=2024.8.30=hbcca054_0
  - cairo=1.16.0=hcf35c78_1003
  - curl=7.71.1=he644dc0_8
  - dbus=1.13.6=hfdff14a_1
  - expat=2.6.3=h5888daf_0
  - ffmpeg=4.3.2=hca11adc_0
  - fontconfig=2.14.0=h8e229c2_0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=7.5.0=habd7529_20
  - gcc_linux-64=7.5.0=h47867f9_33
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=7.5.0=h56cb351_20
  - gfortran_linux-64=7.5.0=h78c8a43_33
  - glib=2.66.3=h58526e2_0
  - glpk=4.65=h9202a9a_1004
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.6=he838d99_2
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - gxx_impl_linux-64=7.5.0=hd0bb8aa_20
  - gxx_linux-64=7.5.0=h555fc39_33
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - icu=64.2=he1b5a44_1
  - jasper=1.900.1=h07fcdf6_1006
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=3.10.0=h4a8ded7_16
  - krb5=1.17.2=h926e7f8_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - leidenalg=0.8.4=py39he80948d_0
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=23_linux64_openblas
  - libcblas=3.9.0=23_linux64_openblas
  - libclang=9.0.1=default_hb4e5071_5
  - libcurl=7.71.1=hcdd3856_8
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=14.1.0=h77fa898_1
  - libgcc-devel_linux-64=7.5.0=hda03d7c_20
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libglib=2.66.3=hbe7bbb4_0
  - libgomp=14.1.0=h77fa898_1
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=23_linux64_openblas
  - liblapacke=3.9.0=23_linux64_openblas
  - libllvm9=9.0.1=default_hc23dcda_4
  - libnghttp2=1.41.0=hab1572f_1
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libopencv=4.5.3=py39h70bf20d_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.16.0=h780b84a_0
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-devel_linux-64=7.5.0=hb016644_20
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hb9d3cd8_1
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - make=4.4.1=hb9d3cd8_1
  - metis=5.1.0=h59595ed_1007
  - mpfr=4.2.1=h9458935_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.69=hb5efdd6_1
  - opencv=4.5.3=py39hf3d152e_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1w=hd590300_0
  - pango=1.42.4=h7062337_4
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.34=h2f06484_0
  - pip=23.3=py39h06a4308_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.3=py39hef51801_1
  - python=3.9.0=h2a148a8_4_cpython
  - python-igraph=0.9.1=py39hfef886c_0
  - python-louvain=0.16=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - qt=5.12.5=hd8c4c69_1
  - r-base=4.0.0=hdca8982_3
  - readline=8.2=h5eee18b_0
  - sed=4.8=he412f7d_0
  - setuptools=68.0.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - suitesparse=5.10.1=h9e50725_1
  - sysroot_linux-64=2.17=h4a8ded7_16
  - texttable=1.7.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tktable=2.10=h0c5db8f_4
  - wheel=0.41.2=py39h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=hb711507_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - anndata==0.10.3
      - array-api-compat==1.4
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - botocore==1.31.17
      - certifi==2023.7.22
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - dask==2024.8.0
      - dask-expr==1.1.10
      - dask-image==2024.5.3
      - datashader==0.17.0
      - debugpy==1.8.5
      - decorator==5.1.1
      - dgl==1.1.2
      - distributed==2024.8.0
      - docrep==0.3.2
      - esda==2.5.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.1.3
      - executing==2.0.1
      - fasteners==0.19
      - filelock==3.13.1
      - fonttools==4.44.0
      - frozenlist==1.6.0
      - fsspec==2023.6.0
      - geopandas==1.0.1
      - get-annotations==0.1.2
      - gseapy==1.1.8
      - h5py==3.10.0
      - idna==3.4
      - igraph==0.10.8
      - imageio==2.37.0
      - importlib-metadata==8.4.0
      - importlib-resources==6.1.1
      - inflect==7.5.0
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - jedi==0.19.1
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.3.2
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - keras-unet-collection==0.1.13
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libpysal==4.8.1
      - llvmlite==0.41.1
      - locket==1.0.0
      - louvain==0.8.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.1
      - matplotlib-inline==0.1.7
      - matplotlib-scalebar==0.9.0
      - matplotlib-venn==1.1.1
      - mdurl==0.1.2
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.3
      - multipledispatch==1.0.0
      - multiscale-spatial-image==1.0.1
      - narwhals==1.33.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - numba==0.58.1
      - numcodecs==0.12.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.52
      - nvidia-nvtx-cu12==12.1.105
      - ome-zarr==0.10.2
      - omnipath==1.0.9
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.0.3
      - param==2.2.0
      - parso==0.8.4
      - partd==1.4.2
      - patsy==0.5.3
      - pexpect==4.9.0
      - pillow==10.1.0
      - pims==0.7
      - platformdirs==4.2.2
      - plotly==6.0.1
      - pluggy==1.5.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.47
      - propcache==0.3.1
      - psutil==5.9.6
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pycparser==2.22
      - pyct==0.5.0
      - pygments==2.18.0
      - pynndescent==0.5.10
      - pyogrio==0.10.0
      - pyparsing==3.1.1
      - pyproj==3.6.1
      - pytest==8.3.3
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - requests==2.31.0
      - rich==14.0.0
      - rpy2==3.1.0
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - s3fs==2023.6.0
      - scanpy==1.9.6
      - scikit-image==0.24.0
      - scikit-learn==1.3.2
      - scikit-misc==0.3.1
      - scipy==1.11.3
      - scprep==1.2.3
      - seaborn==0.12.2
      - session-info==1.0.0
      - shapely==2.0.7
      - simplegeneric==0.8.1
      - six==1.16.0
      - slicerator==1.1.0
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - spatial-image==1.1.0
      - spatialdata==0.2.5.post0
      - squidpy==1.2.0
      - stack-data==0.6.3
      - statsmodels==0.14.0
      - stdlib-list==0.9.0
      - sympy==1.12
      - tbb==2021.10.0
      - tblib==3.1.0
      - threadpoolctl==3.2.0
      - tifffile==2024.8.30
      - tomli==2.0.1
      - toolz==1.0.0
      - torch==2.1.0
      - torch-cluster==1.6.3+pt21cu121
      - torch-geometric==2.4.0
      - torch-scatter==2.1.2+pt21cu121
      - torch-sparse==0.6.18+pt21cu121
      - torch-spline-conv==1.2.2+pt21cu121
      - torchvision==0.16.0
      - tornado==6.4.1
      - tqdm==4.66.1
      - traitlets==5.14.3
      - triton==2.1.0
      - typeguard==4.4.2
      - typing-extensions==4.13.2
      - tzdata==2023.3
      - tzlocal==5.2
      - umap-learn==0.5.4
      - urllib3==1.26.20
      - validators==0.34.0
      - wcwidth==0.2.13
      - wrapt==1.17.2
      - xarray==2024.7.0
      - xarray-dataclasses==1.9.1
      - xarray-datatree==0.0.15
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - yarl==1.20.0
      - zarr==2.18.2
      - zict==3.0.0
      - zipp==3.17.0
prefix: /home/lixiangyu/anaconda3/envs/SpaMOAL
